language: node_js
node_js: "lts/dubnium"

dist: xenial
services:
  - xvfb
addons:
  chrome: stable

script:
  - npm run test -- --no-watch
  - npm run e2e

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
